services:
  shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da:
    image: mongo:7
    container_name: shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da
    networks:
      - app-network
    command: mongod --shardsvr --replSet shard0b0c464c-a3ad-4930-bf06-1d0d6e88c1daReplSet --port 27021 --bind_ip_all
    ports:
      - "27021:27021"
    volumes:
      - shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da-data:/data/db

  shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da-init:
    image: mongo:7
    container_name: shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da-init
    depends_on:
      - shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da
    networks:
      - app-network
    entrypoint: >
      bash -c "
        sleep 15 &&
        mongosh --host shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da:27021 --eval '
          rs.initiate({
            _id: \"shard0b0c464c-a3ad-4930-bf06-1d0d6e88c1daReplSet\",
            members: [{ _id: 0, host: \"shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da:27021\" }]
          })
        ' &&
        sleep 15 &&
        mongosh --host mongos:27020 --eval '
          sh.addShard(\"shard0b0c464c-a3ad-4930-bf06-1d0d6e88c1daReplSet/shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da:27021\");
          sh.splitAt(\"projetnosql.products\", { businessId: \"0b0c464c-a3ad-4930-bf06-1d0d6e88c1da\" });
          sh.moveChunk(\"projetnosql.products\", { businessId: \"0b0c464c-a3ad-4930-bf06-1d0d6e88c1da\" }, \"shard0b0c464c-a3ad-4930-bf06-1d0d6e88c1daReplSet\");
          sh.splitAt(\"projetnosql.producerOrders\", { businessId: \"0b0c464c-a3ad-4930-bf06-1d0d6e88c1da\" });
          sh.moveChunk(\"projetnosql.producerOorders\", { businessId: \"0b0c464c-a3ad-4930-bf06-1d0d6e88c1da\" }, \"shard0b0c464c-a3ad-4930-bf06-1d0d6e88c1daReplSet\");
          print(\"Shard configured for business: 0b0c464c-a3ad-4930-bf06-1d0d6e88c1da\");
        '
      "
    restart: "no"

volumes:
  shard-0b0c464c-a3ad-4930-bf06-1d0d6e88c1da-data: {}

networks:
  app-network:
    external: true
    name: scripts_default
